version: '3'
services:
  lyft_presto_gateway:
    build:
      context: .
      dockerfile: dockerconf/Dockerfile.dev
    image: lyft_presto_gateway
    # image: utk_presto_gateway:v1
    container_name: lyft_presto_gateway
    volumes:
      - .:/app
    environment:
      APP_MODE: dev
      DB_HOST: lyft_mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root123
      ADMIN_PORT: 8091
      APP_PORT: 8090
    entrypoint: /app/dockerconf/entrypoint.sh
    expose:
      - "8091"
      - "8090"
      - "8083"
    ports:
      - 28090:8090
      - 28091:8091
      - 8083:8083
    networks:
      - default
      - presto
    links:
      - lyft_mysql
  lyft_mysql:
    restart: unless-stopped
    image: mysql:8.0.18
    container_name: lyft_mysql
    ports:
    - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: prestogateway
    volumes:
    - ./dockerconf/mysqlconf:/etc/mysql/conf.d
    networks:
      - default
networks:
  presto:
    external: true


  # curl -X POST http://localhost:28090/entity?entityType=GATEWAY_BACKEND -d '{  "name": "presto_stage_k8s", "pro
  



  # curl -X POST http://localhost:8080/v1/statement -H 'X-Presto-User: utk' -d '{"select 1;"}'